url: "https://www.scpi-online.com/scpi/"
list_scpi:
  - scpi-notapierre
  - scpi-corum-origin
  - allianz-home
  - corum-xl
  - remake-live
  - novapierre-1
  - laffitte-pierre
  - activimmo
  - capiforce
  - buroboutic
  - atream-hotels
  - atout-pierre-diversification
  - affinites-pierre
  - allianz-pierre
  - altixia-commerces
  - amundi-delta-capital-sante
  - epargne-pierre
  - pfo2
  - log-in
  - interpierre-france
  - interpierre-europe-centrale
  - immorente
  - aew-patrimoine-sante
  - aew-paris-commerces
  - carac-perspectives-immo
  - genepierre
  - fructiregions-europe
  - atlantique-pierre-1
  - fructipierre
  - france-investipierre
  - scpi-accimmo-pierre
  - scpi-actipierre-europe
  - altixia-cadence-xii
  - scpi-acces-valeur-pierre
  - scpi-metronome
  - aestiam-pierre-rendement
  - aestiam-placement-pierre
  - cap-foncieres-territoires
  - diversification-allemagne
  - atlantique-murs-regions
  - primovie
  - rivoli-avenir-patrimoine
  - selectinvest-1
  - selectipierre-2
  - sofidy-europe-invest
  - sofipierre
  - sofiprime
  - soprorente
  - transitions-europe
  - ufifrance-immobilier
  - unidelta
  - urban-coeur-commerce
  - vendome-regions
  - fonciere-remusat
  - fonciere-des-praticiens
  - primopierre
  - primofamily
  - pierval-sante
  - pierre-plus
  - pierre-expansion-sante
  - pfo
  - pf-grand-paris
  - ficommerce-proximite
  - aestiam-caphebergimmo
  - fair-invest
  - eurovalys
  - pf-hospitalite-europe
  - esg-pierre-capital
  - epsilon-360
  - epargne-pierre-europe
  - epargne-fonciere
  - elysees-pierre
  - patrimmo-croissance
  - patrimmo-commerce
  - opus-real
  - optimale
  - neo
  - novapierre-residentiel
  - novapierre-allemagne-2
  - novapierre-allemagne
  - elialys
  - efimmo-1
  - edissimmo
  - cristal-rente
  - cristal-life
  - credit-mutuel-pierre-1
  - corum-xl
  - corum-origin
  - corum-eurion
  - coeur-de-ville
  - coeur-de-regions
  - notapierre
  - my-share-scpi
  - logipierre-3
  - lf-opportunite-immo
  - coeur-europe
  - lf-grands-palais
  - lf-grand-paris-patrimoine
  - cm-cic-pierre-investissement
  - lf-europimmo
  - lf-avenir-sante
  - le-patrimoine-foncier
  - loustal-des-aveyronnais
  - kyaneos-pierre
  - iroko-zen
  - immorente-2
  - immo-placement
  - scpi-immo-evolutif
  - scpi-gma-essentialis
  - scpi-france-investipierre